import { db, identity, membership, clean, fail, errorResponse, originCheck, json } from '@/lib/database/chat';
import {getAuthUser} from '@/lib/auth/server';
export const dynamic='force-dynamic';
const pair=(a:string,b:string)=>[a,b].sort().join(':');
async function init(id:string){
 const d=db(),auth=await getAuthUser(),now=Date.now();const name=auth?.user_metadata?.display_name||auth?.email?.split('@')[0]||'สมาชิก MC';
 const handle='mc_'+(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(id)).then(b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join(''))).slice(0,12);
 await d.batch([
  d.prepare('INSERT INTO users(id,name,handle,created,seen) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET seen=excluded.seen').bind(id,String(name).slice(0,60),handle,now,now),
  d.prepare("INSERT INTO rooms(id,name,kind,owner,created,updated) VALUES(?,?,'notes',?,?,?) ON CONFLICT DO NOTHING").bind('notes:'+id,'บันทึกของฉัน',id,now,now),
  d.prepare('INSERT INTO members(room,member_id) VALUES(?,?) ON CONFLICT DO NOTHING').bind('notes:'+id,id),
 ]);
}
export async function GET(req:Request){try{
 const id=await identity(),d=db(),u=new URL(req.url),room=u.searchParams.get('room');
 if(room){await membership(room,id);const before=Number(u.searchParams.get('before')||Number.MAX_SAFE_INTEGER);if(!Number.isFinite(before))fail(400,'ช่วงเวลาไม่ถูกต้อง');const beforeId=(u.searchParams.get('beforeId')||'').slice(0,100);const q=(u.searchParams.get('q')||'').slice(0,100);
 const result=await d.prepare(`SELECT m.*,u.name,u.color, r.body reply_body FROM messages m JOIN users u ON u.id=m.sender LEFT JOIN messages r ON r.id=m.reply AND r.deleted=0 WHERE m.room=? AND (m.created<? OR (m.created=? AND m.id<?)) AND (?='' OR m.body LIKE ? ESCAPE E'\\') ORDER BY m.created DESC,m.id DESC LIMIT 51`).bind(room,before,before,beforeId,q,'%'+q.replace(/[\\%_]/g,'\\$&')+'%').all();
 const people=await d.prepare('SELECT u.id,u.name,u.handle,u.bio,u.color,u.seen,mm.read_at AS read FROM members mm JOIN users u ON u.id=mm.member_id WHERE mm.room=?').bind(room).all();
 const react=await d.prepare('SELECT r.message,r.member_id AS "user",r.emoji FROM reactions r JOIN messages m ON m.id=r.message WHERE m.room=? AND m.id IN (SELECT id FROM messages WHERE room=? AND (created<? OR (created=? AND id<?)) ORDER BY created DESC,id DESC LIMIT 51)').bind(room,room,before,before,beforeId).all();
 const attachments=await d.prepare('SELECT id,name,size,type,created FROM files WHERE room=? ORDER BY created DESC LIMIT 100').bind(room).all();
 const mediaIds=result.results.map(m=>String(m.body).match(/\[ไฟล์:([a-zA-Z0-9-]+)\]/)?.[1]).filter((x):x is string=>!!x);const olderMedia=mediaIds.length?await d.prepare('SELECT id,name,size,type,created FROM files WHERE room=? AND id IN ('+mediaIds.map(()=>'?').join(',')+')').bind(room,...mediaIds).all():{results:[]};
 return json({messages:result.results.slice(0,50).reverse(),more:result.results.length>50,people:people.results,reactions:react.results,files:[...new Map([...attachments.results,...olderMedia.results].map(f=>[f.id,f])).values()]});}
 await init(id);
 const me=await d.prepare('SELECT * FROM users WHERE id=?').bind(id).first();
 const rooms=await d.prepare(`SELECT r.*,mm.archived, CASE WHEN r.kind='direct' THEN (SELECT u.name FROM members mx JOIN users u ON u.id=mx.member_id WHERE mx.room=r.id AND mx.member_id<>? LIMIT 1) ELSE r.name END title, (SELECT body FROM messages WHERE room=r.id AND deleted=0 ORDER BY created DESC,id DESC LIMIT 1) last_message, (SELECT count(*) FROM messages WHERE room=r.id AND sender<>? AND created>mm.read_at AND deleted=0) unread FROM members mm JOIN rooms r ON r.id=mm.room WHERE mm.member_id=? ORDER BY r.updated DESC`).bind(id,id,id).all();
 const friends=await d.prepare('SELECT f.*,u.name,u.handle,u.color,u.seen,u.id user_id FROM friends f JOIN users u ON u.id=CASE WHEN f.sender=? THEN f.recipient ELSE f.sender END WHERE f.sender=? OR f.recipient=? ORDER BY f.created DESC').bind(id,id,id).all();
 return json({me,rooms:rooms.results,friends:friends.results});
 }catch(e){return errorResponse(e);}}
export async function POST(req:Request){try{
 originCheck(req);const id=await identity(),d=db();if(Number(req.headers.get('content-length')||0)>16000)fail(413,'ข้อมูลใหญ่เกินไป');let payload:unknown;try{payload=await req.json();}catch{fail(400,'ข้อมูลไม่ถูกต้อง');}const now=Date.now();if(!payload||typeof payload!=='object'||Array.isArray(payload))fail(400,'ข้อมูลไม่ถูกต้อง');const p=payload as Record<string,unknown>;
 if(!await d.prepare('SELECT id FROM users WHERE id=?').bind(id).first())await init(id);
 if(p.action==='profile'){const name=clean(p.name,60),handle=clean(p.handle,30).toLowerCase(),bio=clean(p.bio,160);if(!name||! /^[a-z0-9_]{3,30}$/.test(handle))fail(400,'ชื่อผู้ใช้ต้องเป็น a–z, 0–9 หรือ _ จำนวน 3–30 ตัว');if(await d.prepare('SELECT 1 FROM users WHERE handle=? AND id<>?').bind(handle,id).first())fail(409,'ชื่อผู้ใช้นี้ถูกใช้แล้ว');await d.prepare('UPDATE users SET name=?,handle=?,bio=? WHERE id=?').bind(name,handle,bio,id).run();return json({ok:true});}
 if(p.action==='friend'){const handle=clean(p.handle,30).replace(/^@/,'').toLowerCase();const other=await d.prepare('SELECT id FROM users WHERE handle=?').bind(handle).first<{id:string}>();if(!other)fail(404,'ไม่พบชื่อผู้ใช้นี้ เพื่อนต้องเข้าใช้งาน MC Chat ก่อน');if(other.id===id)fail(400,'นี่คือชื่อผู้ใช้ของคุณ');const exists=await d.prepare('SELECT * FROM friends WHERE pair=?').bind(pair(id,other.id)).first();if(exists)fail(409,exists.status==='accepted'?'เป็นเพื่อนกันแล้ว':'มีคำขอเป็นเพื่อนอยู่แล้ว');await d.prepare('INSERT INTO friends(id,sender,recipient,pair,status,created) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,other.id,pair(id,other.id),'pending',now).run();return json({ok:true});}
 if(p.action==='friend_response'){const fid=clean(p.id,100);const f=await d.prepare("SELECT * FROM friends WHERE id=? AND recipient=? AND status='pending'").bind(fid,id).first();if(!f)fail(404,'ไม่พบคำขอ');if(p.accept)await d.prepare("UPDATE friends SET status='accepted' WHERE id=?").bind(fid).run();else await d.prepare('DELETE FROM friends WHERE id=?').bind(fid).run();return json({ok:true});}
 if(p.action==='room'){const ids:string[]=Array.isArray(p.users)?[...new Set<string>(p.users.map((x:unknown)=>clean(x,200)))].filter(x=>x!==id):[];if(ids.length<1||ids.length>30)fail(400,'เลือกเพื่อน 1–30 คน');for(const other of ids){if(!await d.prepare("SELECT 1 FROM friends WHERE pair=? AND status='accepted'").bind(pair(id,other)).first())fail(403,'สนทนาได้กับเพื่อนที่ตอบรับแล้ว');}const kind=p.group?'group':'direct';if(kind==='direct'&&ids.length!==1)fail(400,'เลือกเพื่อนหนึ่งคน');const key=kind==='direct'?pair(id,ids[0]):null;if(key){const old=await d.prepare('SELECT id FROM rooms WHERE pair=?').bind(key).first();if(old){await d.prepare('UPDATE members SET archived=0 WHERE room=? AND member_id=?').bind(old.id,id).run();return json({id:old.id});}}
 const name=kind==='group'?clean(p.name,80):'ข้อความส่วนตัว';if(!name)fail(400,'กรุณาตั้งชื่อกลุ่ม');const rid=crypto.randomUUID();await d.batch([d.prepare('INSERT INTO rooms(id,name,kind,owner,pair,created,updated) VALUES(?,?,?,?,?,?,?)').bind(rid,name,kind,id,key,now,now),...[id,...ids].map(user=>d.prepare('INSERT INTO members(room,member_id) VALUES(?,?)').bind(rid,user))]);return json({id:rid});}
 const room=clean(p.room,250);await membership(room,id);
 if(p.action==='read'){const through=Number(p.through);if(!Number.isFinite(through)||through>now)fail(400,'เวลาไม่ถูกต้อง');await d.prepare('UPDATE members SET read_at=GREATEST(read_at,?) WHERE room=? AND member_id=?').bind(through,room,id).run();return json({ok:true});}
 if(p.action==='archive'){await d.prepare('UPDATE members SET archived=? WHERE room=? AND member_id=?').bind(p.archived?1:0,room,id).run();return json({ok:true});}
 if(p.action==='message'){const body=clean(p.body,4000),mid=clean(p.id,100);if(!body||! /^[a-zA-Z0-9-]{10,100}$/.test(mid))fail(400,'กรุณาพิมพ์ข้อความ');if(p.reply&&!await d.prepare('SELECT 1 FROM messages WHERE id=? AND room=? AND deleted=0').bind(clean(p.reply,100),room).first())fail(400,'ไม่พบข้อความที่ตอบกลับ');const prior=await d.prepare('SELECT id,room,sender FROM messages WHERE id=?').bind(mid).first();if(prior){if(prior.room!==room||prior.sender!==id)fail(409,'รหัสข้อความซ้ำ');return json({ok:true});}const recent=await d.prepare('SELECT count(*) n FROM messages WHERE sender=? AND created>?').bind(id,now-60000).first<{n:number}>();if((recent?.n||0)>=60)fail(429,'ส่งข้อความเร็วเกินไป กรุณารอสักครู่');await d.batch([d.prepare('INSERT INTO messages(id,room,sender,body,created,reply) VALUES(?,?,?,?,?,?)').bind(mid,room,id,body,now,p.reply||null),d.prepare('UPDATE rooms SET updated=? WHERE id=?').bind(now,room),d.prepare('UPDATE members SET archived=0 WHERE room=?').bind(room)]);return json({ok:true});}
 if(p.action==='edit'||p.action==='delete'){const mid=clean(p.id,100);if(!await d.prepare('SELECT 1 FROM messages WHERE id=? AND room=? AND sender=? AND deleted=0').bind(mid,room,id).first())fail(403,'แก้ไขได้เฉพาะข้อความของคุณ');const body=p.action==='delete'?'ข้อความถูกลบแล้ว':clean(p.body,4000);if(!body)fail(400,'ข้อความต้องไม่ว่าง');await d.prepare('UPDATE messages SET body=?,edited=?,deleted=? WHERE id=?').bind(body,now,p.action==='delete'?1:0,mid).run();return json({ok:true});}
 if(p.action==='react'){const mid=clean(p.id,100),emoji=clean(p.emoji,10);if(!['❤️','👍','😂','🎉'].includes(emoji))fail(400,'อีโมจิไม่ถูกต้อง');if(!await d.prepare('SELECT 1 FROM messages WHERE id=? AND room=? AND deleted=0').bind(mid,room).first())fail(404,'ไม่พบข้อความ');const r=await d.prepare('SELECT 1 FROM reactions WHERE message=? AND member_id=? AND emoji=?').bind(mid,id,emoji).first();if(r)await d.prepare('DELETE FROM reactions WHERE message=? AND member_id=? AND emoji=?').bind(mid,id,emoji).run();else await d.prepare('INSERT INTO reactions(message,member_id,emoji) VALUES(?,?,?) ON CONFLICT DO NOTHING').bind(mid,id,emoji).run();return json({ok:true});}
 fail(400,'ไม่รู้จักคำสั่ง');
 }catch(e){return errorResponse(e);}}
