'use client';
import {useEffect,useRef,useState} from 'react';
import {ImagePlus,Mic,Paperclip,Square,Send,LoaderCircle,Upload,RotateCcw,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {createSupabaseBrowser} from '@/lib/auth/client';
import {MAX_FILE_SIZE,normalizeType} from '@/lib/media/validation';
type Props={room:string;disabled:boolean;onUploaded:()=>Promise<void>;onBusy:(busy:boolean)=>void};
export default function MediaComposer({room,disabled,onUploaded,onBusy}:Props){
 const [mode,setMode]=useState<'image'|'audio'|'file'|null>(null),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[recording,setRecording]=useState(false),[requesting,setRequesting]=useState(false),[seconds,setSeconds]=useState(0),[sending,setSending]=useState(false),[failure,setFailure]=useState('');
 const imageInput=useRef<HTMLInputElement>(null),audioInput=useRef<HTMLInputElement>(null),fileInput=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),epoch=useRef(0),timer=useRef<ReturnType<typeof setInterval>|null>(null),uploadId=useRef(''),lock=useRef(false);
 function release(){if(timer.current){clearInterval(timer.current);timer.current=null;}const r=recorder.current;recorder.current=null;if(r){r.onstop=null;r.onerror=null;r.ondataavailable=null;if(r.state!=='inactive')r.stop();}stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;}
 function close(){if(lock.current)return;epoch.current++;release();setRecording(false);setRequesting(false);setMode(null);setFile(null);setSeconds(0);setFailure('');}
 useEffect(()=>()=>{epoch.current++;release();},[]);
 useEffect(()=>{close();},[room]);
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 function selectFile(f:File){if(f.size===0||f.size>MAX_FILE_SIZE){toast.error('เลือกไฟล์ขนาดไม่เกิน 10 MB');return;}setFailure('');setFile(f);uploadId.current=crypto.randomUUID();const type=normalizeType(f.type,f.name);setMode(type.startsWith('image/')?'image':type.startsWith('audio/')?'audio':'file');}
 function stop(){const r=recorder.current;if(r&&r.state!=='inactive')r.stop();}
 async function start(){
 if(recording||requesting||sending)return;
 if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setFailure('เบราว์เซอร์นี้อัดเสียงไม่ได้ เลือกไฟล์เสียงจากเครื่องแทนได้');return;}
 setFailure('');setFile(null);setSeconds(0);setRequesting(true);const ticket=++epoch.current;
 try{const input=await navigator.mediaDevices.getUserMedia({audio:true});if(ticket!==epoch.current){input.getTracks().forEach(t=>t.stop());return;}stream.current=input;
 const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const rec=new MediaRecorder(input,mime?{mimeType:mime}:undefined);recorder.current=rec;const chunks:Blob[]=[];let size=0;
 rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>MAX_FILE_SIZE&&rec.state!=='inactive')rec.stop();}};
 rec.onstop=()=>{if(timer.current){clearInterval(timer.current);timer.current=null;}input.getTracks().forEach(t=>t.stop());stream.current=null;recorder.current=null;if(ticket!==epoch.current)return;setRecording(false);const type=normalizeType(rec.mimeType||chunks[0]?.type||'audio/webm'),blob=new Blob(chunks,{type});if(!blob.size){setFailure('ไม่พบเสียงที่บันทึก ลองอัดอีกครั้ง');return;}if(blob.size>MAX_FILE_SIZE){setFailure('เสียงมีขนาดเกิน 10 MB กรุณาอัดใหม่ให้สั้นลง');return;}const ext=type==='audio/mp4'?'m4a':type==='audio/ogg'?'ogg':type==='audio/wav'?'wav':'webm';selectFile(new File([blob],'ข้อความเสียง-'+new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')+'.'+ext,{type}));};
 rec.onerror=()=>{epoch.current++;release();setRecording(false);setFailure('บันทึกเสียงไม่สำเร็จ กรุณาลองอีกครั้ง หรือเลือกไฟล์เสียง');};
 rec.start(1000);setRequesting(false);setRecording(true);const began=Date.now();timer.current=setInterval(()=>{const elapsed=Math.floor((Date.now()-began)/1000);setSeconds(elapsed);if(elapsed>=120&&rec.state!=='inactive')rec.stop();},250);
 }catch(e){if(ticket!==epoch.current)return;release();setRequesting(false);setRecording(false);setFailure((e as Error).name==='NotAllowedError'?'กรุณาอนุญาตไมโครโฟน หากเปิดในแอปให้ลองเปิดเว็บใน Safari หรือ Chrome หรือเลือกไฟล์เสียงแทน':'เปิดไมโครโฟนไม่ได้ กรุณาตรวจการเชื่อมต่อ หรือเลือกไฟล์เสียงแทน');}
 }
 async function send(){if(!file||!room||lock.current)return;lock.current=true;setSending(true);onBusy(true);setFailure('');const id=uploadId.current;
 try{const authorize=await fetch('/api/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'authorize',room,id})});const grant=await authorize.json() as {error?:string;complete?:boolean;path?:string;token?:string};if(!authorize.ok)throw new Error(grant.error||'เตรียมอัปโหลดไม่สำเร็จ');
 if(!grant.complete){if(!grant.path||!grant.token)throw new Error('ข้อมูลอัปโหลดไม่ครบ');const supabase=createSupabaseBrowser(),type=normalizeType(file.type,file.name);const {error}=await supabase.storage.from(process.env.NEXT_PUBLIC_STORAGE_BUCKET||'mc-chat').uploadToSignedUrl(grant.path,grant.token,file,{contentType:type,upsert:true});if(error)throw error;const complete=await fetch('/api/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'complete',room,id,name:file.name,type,size:file.size})});const result=await complete.json() as {error?:string};if(!complete.ok)throw new Error(result.error||'บันทึกไฟล์ไม่สำเร็จ');}
 lock.current=false;setSending(false);onBusy(false);close();toast.success('ส่งแล้ว');await onUploaded().catch(()=>toast.info('ส่งสำเร็จแล้ว กำลังรอโหลดบทสนทนา'));
 }catch(e){setFailure((e as Error).message||'เชื่อมต่อไม่สำเร็จ กดส่งอีกครั้งได้');}finally{lock.current=false;setSending(false);onBusy(false);}}
 return <><button className="icon-button" type="button" disabled={disabled||!room} aria-label="ส่งรูปภาพ" title="ส่งรูปภาพ" onClick={()=>imageInput.current?.click()}><ImagePlus/></button><button className="icon-button mic-button" type="button" disabled={disabled||!room} aria-label="ส่งข้อความเสียง" title="ส่งข้อความเสียง" onClick={()=>{setMode('audio');setFailure('');}}><Mic/></button><button className="icon-button" type="button" disabled={disabled||!room} aria-label="แนบไฟล์" title="แนบไฟล์" onClick={()=>fileInput.current?.click()}><Paperclip/></button>
 <input hidden ref={imageInput} type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)selectFile(f);e.target.value='';}}/><input hidden ref={audioInput} type="file" accept="audio/*,.m4a,.mp3,.wav,.ogg,.webm" onChange={e=>{const f=e.target.files?.[0];if(f)selectFile(f);e.target.value='';}}/><input hidden ref={fileInput} type="file" accept=".jpg,.jpeg,.png,.webp,.gif,.pdf,.txt,.zip,.m4a,.mp3,.wav,.ogg,.webm" onChange={e=>{const f=e.target.files?.[0];if(f)selectFile(f);e.target.value='';}}/>
 <Dialog open={!!mode} onOpenChange={o=>{if(!o)close();}}><DialogContent className="media-dialog" showCloseButton={!sending}><DialogHeader><DialogTitle>{mode==='image'?'ส่งรูปภาพ':mode==='audio'?'ข้อความเสียง':'ส่งไฟล์'}</DialogTitle><DialogDescription>{mode==='audio'?'อัดได้ครั้งละ 2 นาที ฟังก่อนส่ง หรือเลือกไฟล์เสียงจากเครื่อง':'ตรวจสอบไฟล์ก่อนส่ง · ขนาดสูงสุด 10 MB'}</DialogDescription></DialogHeader>
 {failure&&<div className="media-error" role="alert">{failure}</div>}
 {mode==='audio'&&!file&&<div className="recording-surface"><div className={'recording-icon '+(recording?'is-recording':'')}><Mic size={35}/></div><strong className="recording-clock">{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong><p aria-live="polite">{requesting?'กำลังขอใช้ไมโครโฟน…':recording?'กำลังอัดเสียง…':'พร้อมแชร์ความรู้ด้วยเสียงของคุณ'}</p>{recording?<button type="button" className="primary stop-recording" onClick={stop}><Square size={17}/>หยุดอัด</button>:<button type="button" className="primary" disabled={requesting} onClick={start}>{requesting?<LoaderCircle className="spin" size={18}/>:<Mic size={18}/>}เริ่มอัดเสียง</button>}<button type="button" className="audio-file-button" disabled={recording||requesting} onClick={()=>audioInput.current?.click()}><Upload size={16}/>เลือกไฟล์เสียงจากเครื่อง</button></div>}
 {file&&<><div className="media-preview">{mode==='image'?<img src={preview} alt="รูปที่เลือกเพื่อส่ง" onError={()=>setFailure('เปิดภาพตัวอย่างไม่ได้ ลองเลือกไฟล์ JPG หรือ PNG ใหม่')}/>:mode==='audio'?<audio key={preview} src={preview} controls preload="metadata" onError={()=>setFailure('เบราว์เซอร์นี้เปิดเสียงตัวอย่างไม่ได้ ลองใช้ MP3 หรือ M4A')}/>:<Paperclip size={35}/>}</div><div className="media-file-label"><strong>{file.name}</strong><small>{(file.size/1024/1024).toFixed(2)} MB</small></div><div className="media-send-actions"><button type="button" className="secondary" disabled={sending} onClick={()=>{setFile(null);setFailure('');if(mode!=='audio')close();}}>{mode==='audio'?<RotateCcw size={17}/>:<Trash2 size={17}/>} {mode==='audio'?'อัดใหม่':'ยกเลิก'}</button><button type="button" className="primary" disabled={sending} onClick={send}>{sending?<LoaderCircle className="spin" size={17}/>:<Send size={17}/>} {sending?'กำลังส่ง…':'ส่ง'+(mode==='image'?'รูปภาพ':mode==='audio'?'ข้อความเสียง':'ไฟล์')}</button></div></>}
 </DialogContent></Dialog></>;
}
